ifndef TARGET
TARGET=z1
endif


all: receiver-side-node2  sender-side-sink  receiver-side-node3 noeud2 noeud3 sink
APPS=servreg-hack
CONTIKI=../../..

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
 
